### ISSUE TITLE
IC2Classic crashes with unidict

### ISSUE THREAD

**Issue by Speiger** [WanionCane/UniDict#109]
You crafting discoverer searches IC2Experimental which crashes with IC2Classic which just got ported to 1.12
could you please add a detection that disables the IC2Experimental discoverer when IC2Classic is loaded?

https://github.com/WanionCane/UniDict/blob/1.12.2/src/main/java/wanion/unidict/integration/CraftingIntegration.java#L53

just add if (Loader.isModLoaded("ic2") && !Loader.isModLoaded("ic2-classic-spmod"))
so that ic2c is at least startable with the mod?

**Comment by WanionCane** [comment]
I will create a fix for this as soon as possible =P

**Comment by WanionCane** [comment]
after taking a look, I found a few things:

if IC2 Classic is present, these mods crashes:

> Immersive Engineering
> Tech Reborn

the other issue is, the default UniDict IC2 Integration doesn't work with IC2 Classic.

the exception on both cases is `java.lang.NoClassDefFoundError`

unfortunately, due to the way I coded the integration handling, these exception is crashing the IntegrationModule,, which is making it to not run all the integrations =/
so, I will have to black list IC2 Classic to not activate IC2 Integration if it is loaded.
and, IC2 Classic will need a specific integration, and for now, I really don't have time to work on it. =/ 

#sorry #sorryForMyEnglish =P

**Comment by Speiger** [comment]
no worry, as long the mod runs with ic2c even if ic2c isnt effected is i think more important.
If you want i can make a compat where you can easier override the inputs in IC2 once you have some time to talk.
IE crashes because of the Classic compat detection is broken. they fixed that just like 5 mins ago.
Techreborn well that isn't supported by IC2C anyway. Because its very buggy on its own.

**Comment by WanionCane** [comment]
ok, now UniDict isn't crashing anymore when IC2 Classic is present XD
so, about a new compact way for overriding the outputs on IC2, you mean the original IC2, or the Classic? XD
I don't think there is need for changing the original IC2 integration, but, if there is a way for changing IC2 Classic recipes as easy as the original IC2 recipes , then it would be very easy to me to create an integration for IC2Classic =P
just the `Recipe Researcher` would be a real pain.. =P

**Comment by Speiger** [comment]
Well adding a API for you should make it a lot easier.
If you want to join my discord we can talk about that in detail.

**Comment by WanionCane** [comment]
ok sure =D
but, I have to sleep now, so hope you don't mind I joining then getting offline right after that XD
