### ISSUE TITLE
Forge hammer broken

### ISSUE THREAD

**Issue by pacmansaysnom** [WanionCane/UniDict#124]
Running a server with the latest version of UniDict and the forge hammer currently will not make plates out of any metal we try.

**Comment by WanionCane** [comment]
oh no, not again... =/
Happy New Year! =D

**Comment by lolhack2000** [comment]
Same for me @WanionCane 
-UniDict-1.12.2-2.9.3
-industrialcraft-2-2.8.187
Crafting Iron Plates with Forge Hammer is not working :(

**Comment by ElektroKill** [comment]
Hello, Sorry for the extremely extremely late response but I have identified the cause of the issue and I am looking at the best solution now.

**Comment by lolhack2000** [comment]
Hey buddy its never to late ;)

**Comment by ElektroKill** [comment]
Okay, the problem is with how UniDict registers its new recipes to the recipe registry. UniDict creates a registry key based on the recipe type (shapeless vs. shaped), the number of ingredients, ore dictionary name of the output, and the amount of the output item. This causes a problem since the Immersive Engineering hammer recipe for iron plates is the receives the same recipe key as the new one from IC2 because the two recipes are identical besides the actual hammer. When two recipes with the same key are registered it causes forge to discard one of them(in this case the one from IC2). The solution to this is to improve the key generation to differentiate between these recipes. The problem with this is that some config options in UniDict rely on the recipe keys for blacklisting. This would break the existing configurations of the mod. I am still in the process of figuring out the best way to handle this problem. I hope this is understandable!
