### ISSUE TITLE
Railcraft

### ISSUE THREAD

**Issue by ComputerErika** [WanionCane/UniDict#128]
So recently rail craft updated to 1.12.2 and it drives me nuts to where I don't even use it that it has a bunch of resources that aren't unified with the others! I love this mod and I am begging you to please add Railcraft support! I don't really know much about java coding and modding Minecraft but to me, now please correct me if I'm wrong, that after you set up a unification system it's not hard to add some more support... It would be a great help! 😊

**Comment by ComputerErika** [comment]
Ok for some reason now it is working... sorry about that.

**Comment by Staegrin** [comment]
Sadly it seems to be random if it unifies or not for Railcraft ingots/nuggets. When I turn 9 thermal expansion ingots into blocks and turn the block back into ingots I get the Railcraft variants. copper/tin/lead/silver/nickel/zinc/steel

Maby because railcraft isn't included in integrationModule.cfg

Railcraft was the last mod updated added to the pack so it's materials take precedence?

random unifying happens for instance when I put the railcraft variants of the ingots into the manual rolling machine and leave the gui (-> you have to keep looking into the gui to make the machine work) then the thermal variants get spit out.
