### ISSUE TITLE
[Suggestion] Add integration for my mod ic2c extras.

### ISSUE THREAD

**Issue by Trinsdar** [WanionCane/UniDict#137]
It would be nice to be able to unify recipes from my roller and my metal bender, the latter when i add the ability to remove recipes from it. Link to curseforge page can be found [here](https://minecraft.curseforge.com/projects/ic2c-extras).

**Comment by WanionCane** [comment]
sorry, I am no longer working on UniDict for 1.12.2, but if you update it to 1.14, I will take a look on it.
and if your project is open source, it would be cool if I could sent you a pull request with the integration, so if you make any changes on your crafting mechanics, you would have to update the integration.
I am saying this because everytime a mod updates I get concern that it broke an integration so I have to re-do it all over again.. =/

**Comment by Trinsdar** [comment]
I probably will update to 1.14 in the future, so therefore yah you could do that once i do update

**Comment by ElektroKill** [comment]
Should be released in UniDict 3.0.4, sorry for the extremely long response time.
