### ISSUE TITLE
Induction Smelter unification not working

### ISSUE THREAD

**Issue by Endoman123** [WanionCane/UniDict#171]
There's an issue with Thermal Expansion Induction Smelters where dusts are not unified properly. Apparently it's an issue with how they implement the inputs of the smeltery, not entirely sure. Apparently [this](https://github.com/jaredlll08/ModTweaker/issues/604#issuecomment-366715797) gives a bit of an explanation as to what's happening behind the scenes, but I've got no great understanding of the implications.

To replicate:
1. Unify lead dusts such that another mod overwrites Thermal Foundation dusts
2. Attempt to create Hardened Glass using the induction smelter
3. Fail

This issue may have side effects with the other Thermal Expansion machines, but I have not looked into it.

**Comment by ElektroKill** [comment]
This is because Thermal Expansion doesn't use OreDict for input. Currently, UniDict only replaces the outputs of TE machines. This would probably need a feature like Mekanism Inpit Replacement. Such a feature would get the correct OreDict entry for the input and then update the recipe accordingly. I will have t see if I could support this in my PR for 3.0.0 changes :)
