### ISSUE TITLE
unable to make ingots with Agricultural Expansion

### ISSUE THREAD

**Issue by UnNinja** [WanionCane/UniDict#2]
[Agricultural Expansion](http://minecraft.curseforge.com/projects/agricultural-expansion) (a sort of magical crops clone) essences can not be made into ingots for metals listed under S:metalsToUnify

tested with unidict 1.9.4-1.5b and Agriculturial expansion beta 1.1.13

**Comment by WanionCane** [comment]
hi, sorry about that.
UniDict remove the recipes (because there is no way to change the output of a recipe after it is created) and then it recreate them.
so, when it is not "ready" for some specific recipe, it just remove it and never create it again.
currently it is working this way: [wanion.unidict.integration.CraftingIntegration.java](https://github.com/WanionCane/UniDict/blob/master/src/main/java/wanion/unidict/integration/CraftingIntegration.java)
once i finish the new algorithm, won't will be need to the recipes be created manually (everything will be dynamic).
thanks.

**Comment by WanionCane** [comment]
can you try with this? [UniDict-1.10.1-2d.](https://github.com/WanionCane/UniDict/releases/tag/1.10.2-1.2d)
it should work.

**Comment by WanionCane** [comment]
since there is no answer, and in my test everything went fine, i will close the issue.

**Comment by slidingmike** [comment]
Can confirm. No issues on my latest update.

**Comment by WanionCane** [comment]
thank you for the answer.

took a while to rewrite the crafting integration, to it be able to generate recipes dynamically;
this will make this kind of issue less likely to happen again.
