### ISSUE TITLE
Forestry and Thermal Foundation Gears

### ISSUE THREAD

**Issue by Xiaminou** [WanionCane/UniDict#45]
When using Unidict with Forestry and Thermal Foundation Bronze, Copper and Tin Gears use Forestry's recipe which requires a stone gear instead of Thermal Foundation's recipe which requires an iron ingot. They end up needing Forestry's Impregnated Sticks. Which means they're gated behind Forestry's progression.
Now I have tried to fix it by editing the .cfg telling it not to mess with those recipes and making sure thermal foundation is higher on the priority list, but nothing is working.
Here is the config file: [UniDict.txt](https://github.com/WanionCane/UniDict/files/1464810/UniDict.txt)
![2017-11-12_16 25 07](https://user-images.githubusercontent.com/8670392/32700611-b290fcba-c7c7-11e7-8528-32b1788d71cf.png)

**Comment by WanionCane** [comment]
hello, you want the Forestry gear to be the output?
if so, you have to give it a higher priority on the config. "forestry" has to be the first of the list instead of the last one.
about the recipes to ignore, see "thermalfoundation:material:256" to specify the metadata, you have to use **#** instead of **:**
edit: seems that I forgot to include "use # to specify metadata" on the .cfg file =/ sorry

**Comment by Xiaminou** [comment]
I want the recipe to use an iron ingot (thermal foundation recipe) instead of a stone gear (forestry recipe).
Oh I haven't touched item IDs in a while, didn't remember that it needs "#" instead of ":", I will correct that and see if it works.

**Comment by Xiaminou** [comment]
[UniDict.txt](https://github.com/WanionCane/UniDict/files/1464870/UniDict.txt)
Is this correct?
Because it's still using stone gears. Still saying it's a Unidict recipe.

**Comment by WanionCane** [comment]
since 1.12, recipes now have names, so, in order to use this feature you must be sure about the recipe name,
to find the recipe name, in your case, is below "Recipe by: #mod"
about "by UniDict" recipe, it means that it was made procedurally by Crafting Integration.
but, it shouldn't remove thermal foundation recipes. I will take a look, thanks.

**Comment by Xiaminou** [comment]
https://github.com/faceofcat/Tesla-Core-Lib/issues/24

**Comment by WanionCane** [comment]
hello, sorry for the delay, I took a look, and setting "B:registerGears" to false in teslacorelib.cfg fixes this.
since this never was a UniDict issue, I am closing this =P

**Comment by Xiaminou** [comment]
Well the issue was that Thermal Foundation's recipe should take priority over other recipes because it's set higher in the priority list. And the other issue (which I don't know if it's still happening) was that even when I modified the config to not modify the recipes it still did.
The reason I linked Tesla's issue is because it turned out to be where those weird recipes came from, but it's definitely not what was causing the previously mentioned issues.
